version: 2

models:
  - name: base_slack__messages
    description: >
      Rename/recast fields, and add any placeholder columns. Construct a message_id.
    columns:
      - name: message_id
        tests:
          - unique
          - not_null
